name: inway
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  liquid_swipe: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  hexcolor: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.17
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.4.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  country_picker: ^2.0.19
  pinput: ^5.0.1
  google_maps_flutter: ^2.2.4
  geolocator: ^14.0.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter_icons:
 android: true
 ios: true
 remove_alpha_ios: true
 image_path: "assets/images/logo.png" 
flutter_native_splash:    
  color: "#19191f"
  image: assets/images/logo.png
flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
